### ISSUE TITLE
Understand Curve nonlinear decay

### ISSUE THREAD

**Issue by dbrehmer** [balancednetwork/balanced-java-contracts#1]

**Comment by BennyOptions** [comment]
@nightowl121 please note that I changed the amount of bBALN received for the 1 week and 1 month lockup periods. I had miscalculated in the original post 

https://gov.balanced.network/t/baln-token-economics-enhancement-bbaln/161

**Comment by nightowl121** [comment]
Decay in bBALN balance has been implemented similar to Curve.
