### ISSUE TITLE
Add delegate methods to DEX, Dividends and DAOfund

### ISSUE THREAD

**Issue by dbrehmer** [balancednetwork/balanced-java-contracts#149]
Add a method to DEX, Dividends, and DAOfund to specify the sICX delegation.
This will be the same as the method already on Loans.

**Comment by dbrehmer** [comment]
Like this method in Loans, which is called from governance. https://github.com/balancednetwork/balanced-java-contracts/blob/main/core-contracts/Loans/src/main/java/network/balanced/score/core/loans/LoansImpl.java#L192

**Comment by nightowl121** [comment]
Already deployed on mainnet
