### ISSUE TITLE
Architecture for Cross Chain

### ISSUE THREAD

**Issue by dbrehmer** [balancednetwork/balanced-java-contracts#157]

**Comment by BennyOptions** [comment]
- On the ICON Network, keep track of how much bnUSD has been exported to different networks
- All transactions are always routed through ICON
- During routing (or ICON as final destination), never allow ICON to "import" more bnUSD than was exported to a respective chain
- This isolates risk to individual chains - infinite mint bug on BSC would not impact bnUSD on ICON or Cosmos, for example

**Comment by AntonAndell** [comment]
Yeah this sounds good and when paired with debt limits for the debt limits we should be somewhat safe from total collapse of bnUSD.
