### ISSUE TITLE
Oracle Improvements

### ISSUE THREAD

**Issue by dbrehmer** [balancednetwork/balanced-java-contracts#198]
Double check Band oracle against our ema DEX oracle.
Verify price data  update on ICON with data on Band chain on our backend.
Include price data from other chain oracles with BTP calls.

**Comment by BennyOptions** [comment]
I'd like to include cross-chain oracle data calls as a feature here

**Comment by FezBox** [comment]
We will build a solution for this for the ICON blockchain so we can use it to optimise BTP costs and call fees on top of what balanced needs it to do.

Closing this card
