### ISSUE TITLE
Divide by zero error in Dividends score

### ISSUE THREAD

**Issue by simusud** [balancednetwork/balanced-java-contracts#207]
When continuousDividendsDay is activated on day 1 , while setting up the markets during balanced configuration we will call depositAndBorrow method which also  triggers tokenFallback of Dividends. 
Here in dividends tokenFallback calls **updateTotalWeight** method:
<img width="749" alt="Screen Shot 2022-08-17 at 20 30 06" src="https://user-images.githubusercontent.com/60603625/185169256-b150300c-4664-46f9-a265-4c9f88fccf3c.png">
In updateTotalWeight we divide amount by **getTotalSupply** which is initially zero. 
<img width="598" alt="Screen Shot 2022-08-17 at 20 31 54" src="https://user-images.githubusercontent.com/60603625/185171052-de8f152c-fecc-458e-b300-a631d6f90c5b.png">

Total supply is only set through **updateBalnStake** method which is updated on each stake baln.
As we are just configuring Balanced we won’t have any staked baln so totalSupply is zero which gives divide by zero error.

**Comment by AntonAndell** [comment]
Doing something like this would be fine, only complexity added is the if, else
```
        if (continuousDividendsActive()) {
            BigInteger balnTotalSupply = DividendsTracker.getTotalSupply();
            BigInteger dividendsToDaofund = _value.multiply(dividendsPercentage.get(DAOFUND)).divide(EXA);
            if (balnTotalSupply.equals(BigInteger.ZERO)) {
                dividendsToDaofund = _value;
            } else {
                DividendsTracker.updateTotalWeight(token, _value.subtract(dividendsToDaofund), balnTotalSupply);
            }

            DividendsReceivedV2(_value, getDay(), _value + " tokens received as dividends token: " + token);
            sendToken(daoFund.get(), dividendsToDaofund, token, "Daofund dividends");
```

A slightly less intuitive solution could be to change getTotalSupply method to:

```
    public static BigInteger getTotalSupply() {
        return totalSupply.getOrDefault(BigInteger.ONE);
    }
```

Which would effectively burn the first dividends. But would be fine i think since it will only be during tests
