### ISSUE TITLE
Reduce manual work for fee handler

### ISSUE THREAD

**Issue by AntonAndell** [balancednetwork/balanced-java-contracts#214]
Goal: Reduce governance actions in preparations for complete decentralization.
Each time a new token is added to the DEX it need to be manually added to the fee handler along with a route to baln.
Investigate ways to improve this. 

we could route through quote tokens. All pairs can only be listed against allowed quote tokens on the Dex. However, hard to know what to route to BALN then.
We could also swap everything from dex to BALN if dao still wants the buy pressure

Limits have to be introduced, how much fees of community token has to be gathered in order to processes it. BaseInQuote->priceInLoop is simple way to set a limit.

Claming Fees are cheap, we could also call the fee handler to swap 1 pair every time someone claims to be less dependent on a bot.

**Comment by simusud** [comment]
@AntonAndell  Are we planning to automate setting routes by calling it from add method of dex? Every time a new pool is set up setRoute method will be called along.

**Comment by AntonAndell** [comment]
I am unsure, that would be one way of doing it. But there would also have to be logic to prevent spamming the feeHandler. Preventing more "important" div types to be converted. But setting the fee handling every time a pool is added seems like a decent approach.

**Comment by simusud** [comment]
Please drop down when you get time to think through any other ways of doing it or if we want to use above mentioned approach what sort of preventive measures we need to consider.

**Comment by AntonAndell** [comment]
Will do, will bring it up on our meeting tonight, I am also considering the approach of taking Baln Fees from the quote token only in the exchange function. Would solve all our problems at once, but not entirely sure of the consequences of this.  This would need feeHandler only to have routes for out quote tokens. 

And such it might be enough to do what you mentioned but instead when adding quote tokens

**Comment by AntonAndell** [comment]
Change so that dex only takes fees in quote tokens instead of both sides of an LP.
I think we can do only this for this Issue. No work would be needed for the fee Handler at this point.

We can ignore non routed  fees for now. 

So for balnFees in Dex they should be only in quote token instead of input token

**Comment by simusud** [comment]
Is this the right way to do it:

if(fromToken.equals(quoteToken)
     calculate fee from "value" and subtract it from fromToken
    .....
else
  first swapping "value" to toToken which gives sendAmount and
   calculate fee from "sendAmount" and subtract it from toToken
   .....

**Comment by AntonAndell** [comment]
This would for sure be the simplest way of doing it, but it would affect the swapping calculations since slippage will be slightly higher which could affect arbitrage bots.

Could you also look into doing it in a way where the fee is always taken from the fromToken, but and then swapped after the initial swap. So getFee, calculate new base and quote amounts, then swap the fee. This would still give the exact same result per swap as we have now. But depending on how annoying it is to implement we can go with the above plan. But community would have to be informed properly to a larger extent.

@nightowl121 If you could weigh in also

**Comment by simusud** [comment]
Yeah swapping the fees again will bring us back to same state. What if we swap all balnFees without considering fees in case of fee swap?

**Comment by AntonAndell** [comment]
It wouldn't be a real swap just a few extra math operations in the already called exchange method. You can just think of it like a swap

**Comment by dbrehmer** [comment]
Opting to go with option 1 here - https://gov.balanced.network/t/fee-handler-management-issues/903
