### ISSUE TITLE
MultiCall SCORE for Frontend

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-java-contracts#22]
This contract will have optimized API calls specifically for the frontend. @octocat512, please specify the APIs you would like.

**Comment by octocat512** [comment]
https://github.com/makerdao/multicall
Please reference the github repo.

**Comment by BennyOptions** [comment]
@octocat512 can we solve this issue through using this contract instead? We are not doing any more python upgrades.

https://github.com/balancednetwork/balanced-contracts/blob/5cb18dbf3078776906f18758f16076f52f217014/core_contracts/dex/dex.py#L994
Please add the pool Id field in the response.

**Comment by BennyOptions** [comment]
@mirmich please implement multiCall in Java as-is. No customization
