### ISSUE TITLE
Small trade DEX bug

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-java-contracts#24]
Replace 
"""
new_token2 = int(
            self._pool_total[_id][_fromToken] * self._pool_total[_id][_toToken] / new_token1)
"""

with:
"""
new_token2 = self._pool_total[_id][_fromToken] * self._pool_total[_id][_toToken] // new_token1
"""

Your current code will lead to error when swapping a tiny amount of token.
Example: https://bicon.tracker.solidwallet.io/transaction/0xcde8aea22ea0169077f5a400c47552fc34b753bba96a113e099269e20d0d431e

**Comment by nightowl121** [comment]
This has been addressed in the java contract.
@AntonAndell This was marked as an issue in the python contract too.
