### ISSUE TITLE
POL for DAO Fund

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-java-contracts#255]
Would like Governance / community members to be able to call the following methods on DAO Fund. This is just a starting point, let's discuss further needs:

balnEarnings
- Internal database that is increased when BALN is claimed from Rewards AND from Network Fees

`@external claimRewards`
- calls the "claim" method on rewards
- increases internal database balnEarnings by amount of BALN claimed

`@external claimNetworkFees`
- calls the "claim" method on dividends
- adds newly claimed sICX and bnUSD to DAO Fund balances
- adds newly claimed BALN tokens to balnEarnings database

`@external lockBALN`
- lockAmount = getBalnEarnings
- lock the lockAmount for 4 years
- balnEarnings = 0 (reset balnEarnings to 0 after locking)

`@governanceOnly depositToDex`
- parameters (tokenAddressOne, amountOne, tokenAddressTwo, amountTwo)
- MUST deposit two tokens to the DEX and must supply amounts for each one

`@external supplyLiquidity`
- After the governance vote is accomplished, this calls the "add" (I think?) method to actually SUPPLY the liquidity. I forget which method is to make initial deposits and which is to commit to the pool. This external method is to commit to the pool

`@governanceOnly withdrawLiquidity`
- parameters (poolID, amount)
- amount = amount of LP tokens we want to burn/withdraw for a given poolID
- withdrawn amounts are added to the DAO Fund holdings

**Comment by AntonAndell** [comment]
balnEarnings could potentially be omitted and just locked automatically when claimed. 

depositToDex and supplyLiquidity  could have have a "upper function" doing both, making us able to do both in a vote easily

**Comment by BennyOptions** [comment]
True, good point. One thing that just crossed my mind though is that getBalnEarnings could be used as a statistic tracking API to see how much BALN the DAO has taken off the market via POL. It's actually an interesting way to track DAO cost savings, since liquidity incentives are similar to marketing spend / customer acquisition cost.

**Comment by AntonAndell** [comment]
So balnEarnings should not be reset as mentioned as above then but rather just keep increasing and storing all the baln rewards we get.

**Comment by BennyOptions** [comment]
Updated from original suggestion:

balnEarnings
- Internal database that is increased when BALN is claimed from Rewards

feeEarnings
- Internal database that is increased when network fees are claimed from Dividends
- multi-levelDB that stores both a token address and the fees associated with it

`@external claimRewards`
- calls the "claim" method on rewards
- creates `claimedAmount` as a temp variable to store the amount of BALN receives
- calls `lockBALN(claimedAmount)` to lock the newly claim BALN for 4 years
- calls `balnEarnings.add(claimedAmount)` for stat-tracking purposes

`@external claimNetworkFees`
- calls the "claim" method on dividends
- creates `claimedAmount` as a temp variable to store the amount of BALN receives
- adds newly claimed tokens to DAO Fund balances
- calls `feeEarnings.add(token, claimedAmount)` for each token received as fees (BALN, bnUSD)

`@governanceOnly supplyLiquidity`
- parameters (tokenAddressOne, amountOne, tokenAddressTwo, amountTwo)
- MUST deposit two tokens to the DEX and must supply amounts for each one
- Adds both tokens to the DEX and commits them as liquidity

`@governanceOnly withdrawLiquidity`
- parameters (poolID, amount)
- amount = amount of LP tokens we want to burn/withdraw for a given poolID
- withdrawn amounts are added to the DAO Fund holdings

**Comment by AntonAndell** [comment]
Do we want to track in the daofund the pools we are in or just leave that to the frontend? 
Also if we where to use karma they would give us LP tokens right? Then we would need a function that stakes in a pool. Could be a function callable by any1.
Something like @external StakeLP(BigInteger poolId) which just stakes it all. Or do we ever just wanna hold lp tokens?
