### ISSUE TITLE
Improve position iteration in Loans

### ISSUE THREAD

**Issue by AntonAndell** [balancednetwork/balanced-java-contracts#277]
We have linked lists for each collateral but do not expose those to readers. 
By allowing iteration there we might make liquidation bots more effective.

**Comment by AntonAndell** [comment]
Also they would be able to predict redemptions

**Comment by hetfly** [comment]
Make number of positions against particular collateral type readable as well, please.

ex: for sICX 6000 addresses supplied collateral, 5900 addresses minted bnUSD. For BTCB 120 addresses supplied collateral, 100 of them minted bnUSD
