### ISSUE TITLE
Sell Collateral directly to repay bnUSD debt

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-java-contracts#28]
When a user has their collateral locked, it would be good to allow them to sell the collateral for bnUSD, then have that bnUSD be used to payoff their debt. This was a hotly requested feature during the black swan event leading to lots of locked collateral positions.

Method: sellCollateral
Params: amountOfCollateral in sICX terms

Events: c = collateral sold in sICX terms, d = debt repaid in bnUSD terms

This should look very similar to a rebalancing transaction

**Comment by simusud** [comment]
@dbrehmer I have few questions here. 

1. Shall we allow selling collateral only of those in locked position or for all other positions as well ?
2. Are we allowing user to give amount of collateral they want to sell or just asking them to call the method without params (In this case UI will show the info of how much of their collateral will be sold and debt to be repaid)
3. Shall we add any threshold limit to which the user can sell their collateral.

**Comment by AntonAndell** [comment]
Ill try and answer some.
1. There is no reason to only allow locked positions i think. At least it was not a restriction in the python version
2. In python there was a amount of sICX collateral specified. So now i guess it should be a symbol and amount specified. 
We also need to check that there exists a bnUSD pool for the specific collateral. Also need to check if these pool has sufficient liquidity/accurate pairing. Could be done by another parameter. Something like minimumDebtRepaid. Which is what the user atleast expect to be able to repay with the specified collateral.
3. Don't think any limits are necessary. Just the core ones, can't receive more bnUSD than debt, can't sell more than users collateral.

**Comment by simusud** [comment]
> Ill try and answer some.
> 
> 1. There is no reason to only allow locked positions i think. At least it was not a restriction in the python version
> 2. In python there was a amount of sICX collateral specified. So now i guess it should be a symbol and amount specified.
>    We also need to check that there exists a bnUSD pool for the specific collateral. Also need to check if these pool has sufficient liquidity/accurate pairing. Could be done by another parameter. Something like minimumDebtRepaid. Which is what the user atleast expect to be able to repay with the specified collateral.
> 3. Don't think any limits are necessary. Just the core ones, can't receive more bnUSD than debt, can't sell more than users collateral.

In ans 2.
Are we reverting transaction in case there is no bnUSD pool for specific collateral? And can you little clarify this part- Could be done by another parameter. Something like minimumDebtRepaid. Which is what the user atleast expect to be able to repay with the specified collateral.

**Comment by AntonAndell** [comment]
Yeah reverting there would be fine. 

During a swap we need to make sure the pool is of good health. There will probably be pools for each collateral but it is not guaranteed that it has good liquidity. We need some way of determining if a swap from collateral to bnusd was "good". 

We could put this responsibility on the user with another parameter. Where they say the minimun bnUSD they are okey with for some amount of collateral. But could also be done in some other ways i imagine

**Comment by simusud** [comment]
In order to keep pools in good health, can we add limit to the amount of collateral user can sell? Only certain percentage of pool base token is able to be swapped at a time.

**Comment by AntonAndell** [comment]
It might be enough but it gives no guarantees of how much debt will be repaid. A minimum receive like we have on the dex is there to guarantee that the swapper is okey with the outcome.

**Comment by simusud** [comment]
Yeah got that, dex will handle the verification of minimum receive provided by the user right. And how will user get to know what is the minimum receivable, UI will be showing that value just like in dex swap right?

**Comment by AntonAndell** [comment]
Yeah i think front end should be able to reuse the code they use for the dex swaps. And yeah we just need to send that value to the dex and the dex will handle it
