### ISSUE TITLE
Translate Rewards to Java

### ISSUE THREAD

**Issue by dbrehmer** [balancednetwork/balanced-java-contracts#36]

**Comment by nightowl121** [comment]
contract to be translated:

https://github.com/balancednetwork/balanced-contracts/tree/continuous-integration/core_contracts/rewards

**Comment by BennyOptions** [comment]
Hey @AntonAndell I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/balanced-5f04e2616a8cff0029931c69/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_
