### ISSUE TITLE
Oracle protection on dex

### ISSUE THREAD

**Issue by FezBox** [balancednetwork/balanced-java-contracts#375]
The goal here is to build a halting mechanism if the price of the dex is to far off the Oracle price 

Percentages to be determined before commencing work.

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

 - [ ] **Scenario: Oracle protection on dex**
  - Given the dex price is within a certain percentage of the oracle price
  - When the dex price deviates too far from the oracle price
  - Then a halting mechanism should be triggered to prevent further transactions
  - And an alert should be displayed to the user informing them of the issue

**Comment by AntonAndell** [comment]
SetOracleProtection(BigInteger pid, BigInteger percentage) 
Where precentage is in points, 0 means no protections
Should verify that both symbols have a price on the orcale
