### ISSUE TITLE
Allow for network emission in balanced rewards

### ISSUE THREAD

**Issue by AntonAndell** [balancednetwork/balanced-java-contracts#400]

**Comment by FezBox** [comment]
gonna go to testnet

**Comment by FezBox** [comment]
@AntonAndell is this going to be distributed in icx or sicx

**Comment by AntonAndell** [comment]
i was planning on sICX

**Comment by FezBox** [comment]
@hetfly see above

**Comment by FezBox** [comment]
@AntonAndell can you create bribes with this?

**Comment by FezBox** [comment]
Everything is on testnet - will need to do a network proposal on testnet and some front-end work

**Comment by FezBox** [comment]
Vote through on lisbon - waiting days to make sure all inflation goes where needed.

**Comment by FezBox** [comment]
finish testing this week

**Comment by FezBox** [comment]
Testing passed - pending final review
