### ISSUE TITLE
Update the swap router to include stability fund swaps for cross chain stable swaps

### ISSUE THREAD

**Issue by FezBox** [balancednetwork/balanced-java-contracts#407]
Design and develop the change needed to the smart contract. once done front end work can commence #1276

**Comment by AntonAndell** [comment]
* Add payable and fallback method routeV2
* minRecv and _receiver remains same
* path parameter is replaced with bytes.

Create path as a RLP object (Route):
Simple example on how to use java score RLP encoder/decoder 
https://github.com/balancednetwork/balanced-java-contracts/blob/main/score-lib/src/main/java/network/balanced/score/lib/structs/Point.java
In this version implement stability swap. swap logic should be existent already and can be reused/replicated. But should not break route v1
Route:
// ENUM of actions 
 STATIC INT SWAP : 1
 STATIC INT STABILITY_SWAP : 2
// possibility to add more actions
 Action[] actions:

 
Route Action:
   int action
   Address toToken

**Comment by FezBox** [comment]
Currently being looked at due to some issues around the token routing swaps
