### ISSUE TITLE
Use xCall 2.1 features in Balanced

### ISSUE THREAD

**Issue by AntonAndell** [balancednetwork/balanced-java-contracts#415]
Remove rollback for outgoing messages on ICON and instead use persistent messages.

**Comment by FezBox** [comment]
@AntonAndell, does this change impact any front-end implementations?
And should we be doing any changes on the front end once this is live?

**Comment by AntonAndell** [comment]
Yes, but wont have any breaking changes. Bridge transactions from ICON can be estimated to be slightly cheaper.

**Comment by FezBox** [comment]
@hetfly @0xmilktea @swiftcc624

**Comment by hetfly** [comment]
@AntonAndell can you create an issue in frontend repo when the time comes with required changes please?

**Comment by AntonAndell** [comment]
Yeah will do

**Comment by FezBox** [comment]
Testing still pending on cosmos, evm and move

**Comment by FezBox** [comment]
all tested. Waiting on code review once someone is free

**Comment by FezBox** [comment]
same as above

**Comment by TRSSMG** [comment]
Main Changes Noticed 
1. sendCall method name in xcall mock is renamed to recvCall . New sendCall method created for persistent message
2. sendPersistentCall is introduced in XcallUtils to replace the sendCall to support the persistent call, which does not support the rollback
3. On calling Daofund contract to claim the xcall feee rollback parameter is sent ’false’ replacing previous ‘true’ as the call is now persistent 
4. In the xcall manager contract new method getProtocolsRaw is introduced to get the rlpEncoded protocols for creating envelope for persistent message
5. Rollback massages removed


Tested :
Ran integration tests for asset manager, loans and rewards contracts 


Findings 

Suggestions: 

1. Unused method sendCall in xcallUtils could be removed  

no significant findings
