### ISSUE TITLE
Translate Staking to Java

### ISSUE THREAD

**Issue by dbrehmer** [balancednetwork/balanced-java-contracts#42]

**Comment by BennyOptions** [comment]
Should be completed by end of Feb / early March

**Comment by dbrehmer** [comment]
Unit tests to be finished today 2/24
Change the way accounts with no delegation preference are handled. If there is no preference specified it will just be null for that address. This will reduce the amount of computation required on every sICX transfer.
After unit tests a plan will be written up for the migration and bug fixes. Plan to be reviewed on Monday.

**Comment by dbrehmer** [comment]
Will push translation with tests on Monday
Will post the process document tomorrow.
Will review together the following day.

**Comment by dbrehmer** [comment]
Translated version will be ready to test deployment on testnet on Monday 3/7.
After that the bug fixes will be deployed, then the change to handling of delegation preference.
