### ISSUE TITLE
Single API contract: getPoolStatsForPair

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-java-contracts#44]

**Comment by octocat512** [comment]
call `getPoolStatsForPair` and add poolId in the response of `getPoolStatsForPair`.

```
                'id': poolid,
                'base': self._pool_total[_id][base_token],
                'quote': self._pool_total[_id][quote_token],
                'base_token': base_token,
                'quote_token': quote_token,
                'total_supply': self._total[_id],
                'price': self.getPrice(_id),
                'name': name,
                'base_decimals': self._token_precisions[base_token],
                'quote_decimals': self._token_precisions[quote_token],
                'min_quote': self._get_rewardable_amount(quote_token)
```

**Comment by BennyOptions** [comment]
Current API does not return`'id': poolid`, the request is to make a new API that returns the below:

                'id': poolid,
                'base': self._pool_total[_id][base_token],
                'quote': self._pool_total[_id][quote_token],
                'base_token': base_token,
                'quote_token': quote_token,
                'total_supply': self._total[_id],
                'price': self.getPrice(_id),
                'name': name,
                'base_decimals': self._token_precisions[base_token],
                'quote_decimals': self._token_precisions[quote_token],
                'min_quote': self._get_rewardable_amount(quote_token)

**Comment by nightowl121** [comment]
For context:
https://github.com/balancednetwork/balanced-contracts/commit/5cb18dbf3078776906f18758f16076f52f217014
