### ISSUE TITLE
Implement CI/CD to run tests and checks

### ISSUE THREAD

**Issue by nightowl121** [balancednetwork/balanced-java-contracts#57]
On every PR, a check should run if tests pass and if the contracts gets optimized successfully.
For every PRs against the main integration should also run. 

Building the jar runs the unit tests. Both building jar and optimizing jar requires to run the gradle task of respective projects.

For integration test we would require a local goloop node and run the integration tests against that node. This will probably take a longer time to run.

**Comment by AntonAndell** [comment]
It would also be neat to have the PR to main add the optimized jar to the repo. This way we can also maintain contract updating integrations test against the newest version.

**Comment by robcxyz** [comment]
@AntonAndell - To be clear, are you suggesting to re-commit the optimized jar back to the repo after it passes tests?

**Comment by robcxyz** [comment]
https://github.com/balancednetwork/balanced-java-contracts/pull/69

Would be good to know if you want to have the integration / unit tests triggered from a makefile.  I think this is the right route and can contribute it.  For integration tests, would be nice good to have a docker-compose and if someone could let me know the commands to run the tests against it. Can someone else add that part and I'll take care of the rest?

**Comment by robcxyz** [comment]
My 2 cents @AntonAndell - I would do all that with just code.  Doing recommits back to main is not ideal.  For deployment testing you can just build it.  Releasing an artifact is another story but that would not be in the code.

**Comment by nightowl121** [comment]
We can have the jars and zip files of the deployed contracts in the repo itself and pick it up from there during the integration testing.

**Comment by nightowl121** [comment]
Integration tests has been added to CI now.
