### ISSUE TITLE
Translate baln to Java

### ISSUE THREAD

**Issue by nightowl121** [balancednetwork/balanced-java-contracts#60]

**Comment by dbrehmer** [comment]
Hey @cacomixtle I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/balanced-5f04e2616a8cff0029931c69/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_
