### ISSUE TITLE
Set up Java integration test environment

### ISSUE THREAD

**Issue by dbrehmer** [balancednetwork/balanced-java-contracts#61]

**Comment by dbrehmer** [comment]
Should be done by Monday, February 28th, 2022.

**Comment by AntonAndell** [comment]
I like the helpers provided in the java score examples github. 
https://github.com/icon-project/java-score-examples/tree/master/testinteg

I have started using it for the loans translation and from the looks of it it seems to have a lot of good features. You can basically just copy this over and have working integration tests very fast.
