### ISSUE TITLE
Remove @ScoreClient and @ScoreInterface from interface

### ISSUE THREAD

**Issue by nightowl121** [balancednetwork/balanced-java-contracts#82]
These annotations have specific purposes.
Score client is used when we want to generate helper methods for doing integration tests. Score Interface generates helper methods when we want to perform inter score call. 

Interfaces in the score-lib should be available for both the purposes. The annotations would be better to remove from score-lib interface. New interface should be extended from existing interface and annotate as required.

**Comment by AntonAndell** [comment]
Cant they just generate both?
@ScoreInterface
@ScoreClient
public interface ....

Since is is compiled into the scorelib it should not hurt anything to just generate everything from one place

**Comment by AntonAndell** [comment]
Also trying out contract mocking for unitTests with scoreInterface. Ill tag you in rewards draft and you can take a look and share some thoughts on it.

**Comment by AntonAndell** [comment]
Also trying out contract mocking for unitTests with scoreInterface. Ill tag you in rewards draft and you can take a look and share some thoughts on it.

**Comment by nightowl121** [comment]
Only score interface is necessary, score client is not necessary in interface. All the score client has been removed.
