### ISSUE TITLE
Rebalancing SCORE Review

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-java-contracts#83]
https://github.com/balancednetwork/balanced-java-contracts/tree/main/core-contracts/Rebalancing/src/main/java/network/balanced/score/core/rebalancing

@gedanziger please leave comments here (if any)

From @nightowl121 

Rebalancing score had an issue where we were calculating wrong amount to trade in the reverse rebalancing case.  I have updated the code as well as test. Let me know if there are any comments on it.
https://github.com/balancednetwork/balanced-java-contracts/pull/54

TLDR:
We can get three conditions with price difference.
a. priceDifference > threshold (dex price of bnusd is low),
b. priceDifference < -threshold, (dex price of bnusd is high)
c. priceDifference within [-threshold, threshold] (dex price is within range)

If bnUSD price is less in dex, to increase we would need to add sicx in the pool and get back bnUSD
Buy bnUSD from the pool --> Sell sicx.
Add sicx in the pool i.e. buy bnusd from the pool and sell icx. pair: sicx/bnusd

If bnUSD price is more in dex, to reduce we would need to add bnusd in the pool, and get back sicx
Sell bnUSD to the pool --> buy sicx.
Add bnusd in the pool i.e. buy sicx from the pool and sell bnusd. pair bnusd/sicx
(edited)

In both the conditions we were considering base as sicx and quote as bnusd but in reverse case base is bnusd and quote is sicx. Let me know if there are any issues in my understanding.

**Comment by nightowl121** [comment]
No comments from @gedanziger, and the contract is in mainnet.
