### ISSUE TITLE
Always send continuous rewards data

### ISSUE THREAD

**Issue by dbrehmer** [balancednetwork/balanced-java-contracts#97]
For continuous rewards we will send data with every transaction. To ensure there is no issue during the transition to continuous rewards we will deploy with the data sending enabled, but the rewards contract will do nothing with it until continuous rewards are enabled.

- [x] DEX
- [x] Loans
- [x] StakedLP

**Comment by nightowl121** [comment]
This has been done in all 3 contracts.
